export const screenNames = {
  CHATS_SCREEN: 'CHATS_SCREEN',
  STATUS_SCREEN: 'STATUS_SCREEN',
  CALLS_SCREEN: 'CALLS_SCREEN',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
  TOP_NAV: 'TOP_NAV',
  CAMERA_SCREEN: 'CAMERA_SCREEN',
};
